services:
  mongo:
    image: mongo:8.2.2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: shopping-list

volumes:
  mongo-data:
